--CONSULTA 1
SELECT  SUM(CANTIDAD_COPIAS)
FROM TIENDA, PELICULA_TIENDA, PELICULA
WHERE TIENDA.CODIGO_TIENDA = PELICULA_TIENDA.CODIGO_TIENDA 
    AND PELICULA.CODIGO_PELICULA = PELICULA_TIENDA.CODIGO_PELICULA
    AND PELICULA.TITULO_PELICULA = 'SUGAR WONKA';

--CONSULTA 2
SELECT CLIENTE.NOMBRE_CLIENTE, CLIENTE.APELLIDO_CLIENTE, 
    SUM(RENTA.CANTIDAD_PAGO_RENTA) AS TOTAL
FROM RENTA, CLIENTE
WHERE CLIENTE.CODIGO_CLIENTE = RENTA.CODIGO_CLIENTE
GROUP BY CLIENTE.NOMBRE_CLIENTE, CLIENTE.APELLIDO_CLIENTE
HAVING 40 <= COUNT(*);

--CONSULTA 3
SELECT NOMBRE_ACTOR || ' ' || APELLIDO_ACTOR AS NOMBRE_APELLIDO
FROM ACTOR
WHERE APELLIDO_ACTOR LIKE '%son%'
ORDER BY NOMBRE_ACTOR ASC;

--CONSULTA 4
SELECT DISTINCT NOMBRE_ACTOR, APELLIDO_ACTOR, FECHA_ESTRENO_PELICULA
FROM ACTOR_PELICULA, ACTOR, PELICULA
WHERE PELICULA.DESCRIPCION_PELICULA LIKE '%Crocodile%'
    AND PELICULA.DESCRIPCION_PELICULA LIKE '%Shark%'
    AND ACTOR_PELICULA.CODIGO_ACTOR = ACTOR.CODIGO_ACTOR
    AND ACTOR_PELICULA.CODIGO_PELICULA = PELICULA.CODIGO_PELICULA
ORDER BY APELLIDO_ACTOR ASC;

--CONSULTA 5
SELECT CC.NOMBRE_PAIS, CC.NOMBRE_COMPLETO, CC.RENTAS_MAXIMAS, CD.RENTAS_SUMA, 
    (CC.RENTAS_MAXIMAS * 100)/CD.RENTAS_SUMA AS PORCENTAJE
FROM(
    SELECT CA.NOMBRE_PAIS AS NOMBRE_PAIS, CA.NOMBRE_COMPLETO AS NOMBRE_COMPLETO, CA.RENTAS_MAXIMAS AS RENTAS_MAXIMAS
    FROM(
        SELECT NOMBRE_PAIS , NOMBRE_COMPLETO, RENTAS_MAXIMAS
        FROM(
            SELECT PAIS AS NOMBRE_PAIS , MAX(RENTAS) AS RENTAS_MAXIMAS
            FROM(
                SELECT CLIENTE.CODIGO_CLIENTE, CLIENTE.NOMBRE_CLIENTE || ' ' || CLIENTE.APELLIDO_CLIENTE
                AS NOMBRE_COMPLETO, PAIS.NOMBRE_PAIS AS PAIS, COUNT(*) AS RENTAS
                FROM PAIS, CIUDAD, CLIENTE, RENTA
                WHERE 
                    PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
                    AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
                    AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
                GROUP BY
                    CLIENTE.CODIGO_CLIENTE, CLIENTE.NOMBRE_CLIENTE || ' ' || CLIENTE.APELLIDO_CLIENTE, 
                    PAIS.NOMBRE_PAIS
            ) TA
            GROUP BY PAIS
        )
        MAX_POR_PAIS,
        (
            SELECT CLIENTE.CODIGO_CLIENTE, CLIENTE.NOMBRE_CLIENTE || ' ' || CLIENTE.APELLIDO_CLIENTE
                AS NOMBRE_COMPLETO, PAIS.NOMBRE_PAIS AS PAIS, COUNT(*) AS RENTAS
            FROM PAIS, CIUDAD, CLIENTE, RENTA
            WHERE 
                PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
                AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
                AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
            GROUP BY
                CLIENTE.CODIGO_CLIENTE, CLIENTE.NOMBRE_CLIENTE || ' ' || CLIENTE.APELLIDO_CLIENTE, 
                PAIS.NOMBRE_PAIS

        ) POR_CLIENTE

        WHERE POR_CLIENTE.PAIS = MAX_POR_PAIS.NOMBRE_PAIS 
            AND POR_CLIENTE.RENTAS = MAX_POR_PAIS.RENTAS_MAXIMAS
        ORDER BY
            RENTAS_MAXIMAS DESC LIMIT 1
    ) CA
) CC,
(
    SELECT TD.PAIS AS NOMBRE_PAIS , SUM(RENTAS) AS RENTAS_SUMA
    FROM(
        SELECT CLIENTE.CODIGO_CLIENTE, CLIENTE.NOMBRE_CLIENTE || ' ' || CLIENTE.APELLIDO_CLIENTE
        AS NOMBRE_COMPLETO, PAIS.NOMBRE_PAIS AS PAIS, COUNT(*) AS RENTAS
        FROM PAIS, CIUDAD, CLIENTE, RENTA
        WHERE 
            PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
            AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
            AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
        GROUP BY
            CLIENTE.CODIGO_CLIENTE, CLIENTE.NOMBRE_CLIENTE || ' ' || CLIENTE.APELLIDO_CLIENTE, 
            PAIS.NOMBRE_PAIS
    ) TD
    GROUP BY PAIS
) CD
WHERE 
    CC.NOMBRE_PAIS = CD.NOMBRE_PAIS
;

--CONSULTA 6
SELECT TA.NOMBRE_PAIS, TA.NOMBRE_CIUDAD, TA.CANTIDAD AS CANTIDAD_POR_CIUDAD, TB.CANTIDAD AS CANTIDAD_POR_PAIS, 
    (TA.CANTIDAD::FLOAT * 100)/TB.CANTIDAD::FLOAT AS PORCENTAJE
FROM(
    SELECT PC.PAIS AS NOMBRE_PAIS , PC.CIUDAD AS NOMBRE_CIUDAD,  PC.CANTIDAD_CLIENTES AS  CANTIDAD
    FROM(
        SELECT CIUDAD.NOMBRE_CIUDAD AS CIUDAD,
        PAIS.NOMBRE_PAIS AS PAIS, COUNT(CLIENTE.NOMBRE_CLIENTE) AS CANTIDAD_CLIENTES
        FROM PAIS, CIUDAD, CLIENTE
        WHERE 
            PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
            AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
        GROUP BY
            CIUDAD.NOMBRE_CIUDAD,
            PAIS.NOMBRE_PAIS
    ) PC
    GROUP BY 
        PAIS, CIUDAD, CANTIDAD_CLIENTES
) TA,
( 
   SELECT PP.PAIS AS NOMBRE_PAIS, PP.CANTIDAD_CLIENTES AS CANTIDAD
    FROM(
        SELECT PAIS.NOMBRE_PAIS AS PAIS, COUNT(CLIENTE.NOMBRE_CLIENTE) AS CANTIDAD_CLIENTES
        FROM PAIS, CIUDAD, CLIENTE
        WHERE 
            PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
            AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
        GROUP BY
            PAIS.NOMBRE_PAIS
        
    ) PP
    GROUP BY 
        PP.PAIS, PP.CANTIDAD_CLIENTES 
) TB
WHERE
    TA.NOMBRE_PAIS = TB.NOMBRE_PAIS
ORDER BY    
    TA.NOMBRE_PAIS ASC
;

--CONSULTA 7
SELECT SUMA_DE_RENTAS.PAIS, SUMA_DE_RENTAS.CIUDAD, SUMA_DE_RENTAS.RENTAS, CIUDADES_POR_PAIS.CIUDADES, SUMA_DE_RENTAS.RENTAS::FLOAT / CIUDADES_POR_PAIS.CIUDADES::FLOAT AS PROMEDIO
FROM(
    SELECT PAIS.NOMBRE_PAIS AS PAIS, COUNT(*) AS RENTAS, CIUDAD.NOMBRE_CIUDAD AS CIUDAD
    FROM PAIS, CIUDAD, CLIENTE, RENTA
    WHERE
        PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
        AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
        AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
    GROUP BY
        PAIS.NOMBRE_PAIS, CIUDAD.NOMBRE_CIUDAD
) SUMA_DE_RENTAS,
(
    SELECT PAIS.NOMBRE_PAIS AS  PAIS, COUNT(*) AS CIUDADES
    FROM PAIS, CIUDAD
    WHERE
        PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
    GROUP BY
        PAIS.NOMBRE_PAIS
) CIUDADES_POR_PAIS
WHERE
    SUMA_DE_RENTAS.PAIS = CIUDADES_POR_PAIS.PAIS
ORDER BY
    PAIS ASC
;

--CONSULTA 8
SELECT CA.PAIS, CA.NO_PELICULAS_CATE_SPORTS, CB.RENTAS_SUMA AS TOTAL_RENTAS_POR_PAIS,
    ((CA.NO_PELICULAS_CATE_SPORTS * 100) / CB.RENTAS_SUMA) AS PORCENTAJE
FROM(
    SELECT TA.PAIS AS PAIS , COUNT(TB.NOMBRE_CATEGORIA) AS NO_PELICULAS_CATE_SPORTS
    FROM(
        SELECT TD.PAIS AS PAIS, TD.CIUDAD , CODIGO_RENTA AS CODIGO_PELICULA
        FROM(
            SELECT CIUDAD.NOMBRE_CIUDAD AS CIUDAD,
            PAIS.NOMBRE_PAIS AS PAIS, RENTA.CODIGO_PELICULA AS CODIGO_RENTA
            FROM PAIS, CIUDAD, CLIENTE, RENTA
            WHERE 
                PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
                AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
                AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
            GROUP BY
                CIUDAD.NOMBRE_CIUDAD,
                PAIS.NOMBRE_PAIS, RENTA.CODIGO_PELICULA
        ) TD
        GROUP BY 
            PAIS, CIUDAD, CODIGO_RENTA
    ) TA,
    (
        SELECT PELICULA.CODIGO_PELICULA AS CODIGO_PELICULA,  PELICULA.TITULO_PELICULA AS TITULO_PELICULA, 
            CATEGORIA.NOMBRE_CATEGORIA AS NOMBRE_CATEGORIA
        FROM PELICULA, CATEGORIA, CATEGORIA_PELICULA
        WHERE
            CATEGORIA.NOMBRE_CATEGORIA = 'Sports'
            AND CATEGORIA_PELICULA.CODIGO_PELICULA = PELICULA.CODIGO_PELICULA
            AND CATEGORIA_PELICULA.CODIGO_CATEGORIA= CATEGORIA.CODIGO_CATEGORIA
        GROUP BY
            PELICULA.CODIGO_PELICULA, PELICULA.TITULO_PELICULA, CATEGORIA.NOMBRE_CATEGORIA           
    ) TB
    WHERE
        TA.CODIGO_PELICULA = TB.CODIGO_PELICULA
    GROUP BY
        PAIS
) CA,
(
    SELECT TD.PAIS AS PAIS , SUM(RENTAS) AS RENTAS_SUMA
    FROM(
        SELECT CIUDAD.NOMBRE_CIUDAD AS CIUDAD,
        PAIS.NOMBRE_PAIS AS PAIS, COUNT(*) AS RENTAS
        FROM PAIS, CIUDAD, CLIENTE, RENTA
        WHERE 
            PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
            AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
            AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
        GROUP BY
            CIUDAD.NOMBRE_CIUDAD,
            PAIS.NOMBRE_PAIS
    ) TD
    GROUP BY 
        PAIS    
) CB
WHERE
    CA.PAIS = CB.PAIS
ORDER BY
    PAIS ASC
;

--CONSULTA 9
SELECT TD.PAIS AS PAIS , TD.CIUDAD, SUM(RENTAS) AS RENTAS_POR_CIUDAD
FROM(
    SELECT CIUDAD.NOMBRE_CIUDAD AS CIUDAD,
    PAIS.NOMBRE_PAIS AS PAIS, COUNT(*) AS RENTAS
    FROM PAIS, CIUDAD, CLIENTE, RENTA
    WHERE 
        PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
        AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
        AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
    GROUP BY
        CIUDAD.NOMBRE_CIUDAD,
        PAIS.NOMBRE_PAIS
) TD
WHERE
    PAIS = 'United States'
GROUP BY 
    PAIS, CIUDAD
HAVING 
    SUM(RENTAS) > (
        SELECT COUNT(*)
        FROM CIUDAD, CLIENTE, RENTA
        WHERE
            CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
            AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
            AND CIUDAD.NOMBRE_CIUDAD = 'Dayton'
        GROUP BY
            CIUDAD.NOMBRE_CIUDAD
    )
ORDER BY
    RENTAS_POR_CIUDAD DESC
;

--CONSULTA 10
SELECT TB.PAIS, TB.CIUDAD, TB.NUMERO_RENTAS
FROM(
    SELECT TA.PAIS, TA.CIUDAD, MAX(RENTAS) AS NUMERO_RENTAS
    FROM(
        SELECT CATEGORIA.NOMBRE_CATEGORIA AS CATEGORIA, PAIS.NOMBRE_PAIS AS PAIS, CIUDAD.NOMBRE_CIUDAD
        AS CIUDAD, COUNT(*) AS RENTAS
        FROM PAIS, CIUDAD, CLIENTE, RENTA, PELICULA, CATEGORIA_PELICULA, CATEGORIA
        WHERE
            PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
            AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
            AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
            AND RENTA.CODIGO_PELICULA = PELICULA.CODIGO_PELICULA
            AND PELICULA.CODIGO_PELICULA = CATEGORIA_PELICULA.CODIGO_PELICULA
            AND CATEGORIA.CODIGO_CATEGORIA = CATEGORIA_PELICULA.CODIGO_CATEGORIA
        GROUP BY
            CATEGORIA.NOMBRE_CATEGORIA, PAIS.NOMBRE_PAIS, CIUDAD.NOMBRE_CIUDAD
    ) TA
    GROUP BY 
        PAIS, CIUDAD
    ORDER BY
        PAIS, CIUDAD
) TB,
(
    SELECT CATEGORIA.NOMBRE_CATEGORIA AS CATEGORIA, PAIS.NOMBRE_PAIS AS PAIS, 
        CIUDAD.NOMBRE_CIUDAD AS CIUDAD, COUNT(*) RENTAS
    FROM PAIS, CIUDAD, CLIENTE, RENTA, PELICULA, CATEGORIA_PELICULA, CATEGORIA
    WHERE
        PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
        AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
        AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
        AND RENTA.CODIGO_PELICULA = PELICULA.CODIGO_PELICULA
        AND PELICULA.CODIGO_PELICULA = CATEGORIA_PELICULA.CODIGO_PELICULA
        AND CATEGORIA.CODIGO_CATEGORIA = CATEGORIA_PELICULA.CODIGO_CATEGORIA
    GROUP BY
        CATEGORIA.NOMBRE_CATEGORIA, PAIS.NOMBRE_PAIS, CIUDAD.NOMBRE_CIUDAD
) TC
WHERE
    CATEGORIA = 'Horror'
    AND TB.PAIS = TC.PAIS
    AND TB.CIUDAD = TC.CIUDAD
    AND TB.NUMERO_RENTAS = TC.RENTAS  
;