
-- BORRADO
TRUNCATE TEMPORAL;

-- CREADO
CREATE TABLE TEMPORAL(

NOMBRE_CLIENTE VARCHAR(100),
CORREO_CLIENTE VARCHAR(100),
CLIENTE_ACTIVO VARCHAR(5),
FECHA_CREACION TIMESTAMP,
TIENDA_PREFERIDA VARCHAR(50),
DIRECCION_CLIENTE VARCHAR(250),
CODIGO_POSTAL_CLIENTE INT,
CIUDAD_CLIENTE VARCHAR(100),
PAIS_CLIENTE VARCHAR(100),
FECHA_RENTA TIMESTAMP,
FECHA_RETORNO TIMESTAMP,
MONTO_A_PAGAR FLOAT,
FECHA_PAGO TIMESTAMP,
NOMBRE_EMPLEADO VARCHAR(100),
CORREO_EMPLEADO VARCHAR(100),
EMPLEADO_ACTIVO VARCHAR(5),
TIENDA_EMPLEADO VARCHAR(50),
USUARIO_EMPLEADO VARCHAR(50),
CONTRASENA_EMPLEADO VARCHAR(250),
DIRECCION_EMPLEADO VARCHAR(150),
CODIGO_POSTAL_EMPLEADO INT,
CIUDAD_EMPLEADO VARCHAR(100),
PAIS_EMPLEADO VARCHAR(100),
NOMBRE_TIENDA VARCHAR(50),
ENCARGADO_TIENDA VARCHAR(100),
DIRECCION_TIENDA VARCHAR(250),
CODIGO_POSTAL_TIENDA INT,
CIUDAD_TIENDA VARCHAR(100),
PAIS_TIENDA VARCHAR(100),
TIENDA_PELICULA VARCHAR(50),
NOMBRE_PELICULA VARCHAR(100),
DESCRIPCION_PELICULA VARCHAR(500),
ANO_LANZAMIENTO VARCHAR(100),
DIAS_RENTA INT,
COSTO_RENTA FLOAT,
DURACION INT,
COSTO_POR_DANO FLOAT,
CLASIFICACION VARCHAR(50),
LENGUAJE_PELICULA VARCHAR(50),
CATEGORIA_PELICULA VARCHAR(100),
ACTOR_PELICULA VARCHAR(100)

);