--BORRRADO
DROP TABLE 
    ACTOR,
    CATEGORIA,
    TRADUCCION, 
    CIUDAD,
    CLIENTE, 
    EMPLEADO,
    PAIS,
    PELICULA,
    PELICULA_TIENDA,
    RENTA,
    TIENDA,
    TRADUCCION,
    CATEGORIA_PELICULA,
    ACTOR_PELICULA,
    TRADUCCION_PELICULA
;


-- CREADO
-- TABLA DE PAISES
CREATE TABLE PAIS(

    CODIGO_PAIS SERIAL PRIMARY KEY,
    NOMBRE_PAIS VARCHAR(50) NOT NULL
    
);

-- TABLA DE CIUDADES
CREATE TABLE CIUDAD(

    CODIGO_CIUDAD SERIAL PRIMARY KEY,
    NOMBRE_CIUDAD VARCHAR(50) NOT NULL,
    CODIGO_POSTAL_CIUDAD INT,
    CODIGO_PAIS INT,
    CONSTRAINT FK_CODIGO_PAIS FOREIGN KEY(CODIGO_PAIS) REFERENCES PAIS(CODIGO_PAIS)

);

-- TABLA DE TIENDAS
CREATE TABLE TIENDA(

    CODIGO_TIENDA SERIAL PRIMARY KEY,
    DIRECCION_TIENDA VARCHAR(100) NOT NULL,
    NOMBRE_TIENDA VARCHAR(50) NOT NULL,
    CODIGO_POSTAL_TIENDA INT

);

-- TABLA DE CLIENTES
CREATE TABLE CLIENTE(

    CODIGO_CLIENTE SERIAL PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR(50) NOT NULL,
    APELLIDO_CLIENTE VARCHAR(50) NOT NULL,
    DIRECCION_CLIENTE VARCHAR(100) NOT NULL,
    CORREO_ELECTRONICO_CLIENTE VARCHAR(100) NOT NULL,
    FECHA_REGISTRO_CLIENTE TIMESTAMP NOT NULL,
    CODIGO_POSTAL_CLIENTE INT,
    ESTADO_CLIENTE VARCHAR(5) NOT NULL,
    CODIGO_TIENDA INT,
    CODIGO_CIUDAD INT,
    CONSTRAINT FK_CODIGO_TIENDA FOREIGN KEY(CODIGO_TIENDA) REFERENCES TIENDA(CODIGO_TIENDA),
    CONSTRAINT FK_CODIGO_CIUDAD FOREIGN KEY(CODIGO_CIUDAD) REFERENCES CIUDAD(CODIGO_CIUDAD)

);

--TABLA DE EMPLEADOS
CREATE TABLE EMPLEADO(

    CODIGO_EMPLEADO SERIAL PRIMARY KEY,
    NOMBRE_EMPLEADO VARCHAR(50) NOT NULL,
    APELLIDO_EMPLEADO VARCHAR(50) NOT NULL,
    DIRECCION_EMPLEADO VARCHAR(100) NOT NULL,
    CORREO_ELECTRONICO_EMPLEADO VARCHAR(100) NOT NULL,
    CODIGO_POSTAL_EMPLEADO INT,
    ESTADO_EMPLEADO VARCHAR(5) NOT NULL,
    USUARIO_EMPLEADO VARCHAR(50) NOT NULL,
    CONTRASENA_EMPLEADO VARCHAR(100) NOT NULL,
    CODIGO_TIENDA INT,
    CONSTRAINT FK_CODIGO_TIENDA FOREIGN KEY(CODIGO_TIENDA) REFERENCES TIENDA(CODIGO_TIENDA)

);

-- TABLA DE PELICULAS
CREATE TABLE PELICULA(

    CODIGO_PELICULA SERIAL PRIMARY KEY,
    TITULO_PELICULA VARCHAR(50) NOT NULL,
    DESCRIPCION_PELICULA VARCHAR(500) NOT NULL,
    FECHA_ESTRENO_PELICULA VARCHAR(100) NOT NULL,
    COSTO_RENTA_PELICULA FLOAT NOT NULL,
    COSTO_MORA_PELICULA FLOAT NOT NULL,
    CLASIFICACION_PELICULA VARCHAR(50) NOT NULL,
    IDIOMA_ORIGEN_PELICULA VARCHAR(50) NOT NULL,
    DURACION_PELICULA INT NOT NULL,
    TIEMPO_RENTA_PELICULA INT NOT NULL
);

-- TABLA CONEXION MM PELICULAS-TIENDA
CREATE TABLE PELICULA_TIENDA(

    CODIGO_PELICULA_TIENDA SERIAL PRIMARY KEY,
    CANTIDAD_COPIAS INT,
    CODIGO_TIENDA INT,
    CODIGO_PELICULA INT,
    CONSTRAINT FK_CODIGO_TIENDA FOREIGN KEY(CODIGO_TIENDA) REFERENCES TIENDA(CODIGO_TIENDA),
    CONSTRAINT FK_CODIGO_PELICULA FOREIGN KEY(CODIGO_PELICULA) REFERENCES PELICULA(CODIGO_PELICULA)

);

-- TABLA RENTA DE PELICULAS
CREATE TABLE RENTA(

    CODIGO_RENTA SERIAL PRIMARY KEY,
    CANTIDAD_PAGO_RENTA FLOAT,
    FECHA_RENTA TIMESTAMP,
    FECHA_RETORNO TIMESTAMP,
    CODIGO_CLIENTE INT,
    CODIGO_EMPLEADO INT,
    CODIGO_PELICULA INT,
    CONSTRAINT FK_CODIGO_CLIENTE FOREIGN KEY(CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE),
    CONSTRAINT FK_CODIGO_EMPLEADO FOREIGN KEY(CODIGO_EMPLEADO) REFERENCES EMPLEADO(CODIGO_EMPLEADO),
    CONSTRAINT FK_CODIGO_PELICULA FOREIGN KEY(CODIGO_PELICULA) REFERENCES PELICULA(CODIGO_PELICULA)

);

-- TABLA DE CATEGORIAS
CREATE TABLE CATEGORIA(

    CODIGO_CATEGORIA SERIAL PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR(50) NOT NULL
    
);

-- TABLA CONEXION MUCHOS-MUCHOS CATEGORIAS-PELICULAS
CREATE TABLE CATEGORIA_PELICULA(

    CODIGO_CATEGORIA_PELICULA SERIAL PRIMARY KEY,
    CODIGO_CATEGORIA INT,
    CODIGO_PELICULA INT,
    CONSTRAINT FK_CODIGO_CATEGORIA FOREIGN KEY(CODIGO_CATEGORIA) REFERENCES CATEGORIA(CODIGO_CATEGORIA),
    CONSTRAINT FK_CODIGO_PELICULA FOREIGN KEY(CODIGO_PELICULA) REFERENCES PELICULA(CODIGO_PELICULA)

);

-- TABLA DE ACTORES
CREATE TABLE ACTOR(

    CODIGO_ACTOR SERIAL PRIMARY KEY,
    NOMBRE_ACTOR VARCHAR(50) NOT NULL,
    APELLIDO_ACTOR VARCHAR(50) NOT NULL
    
);

-- TABLA CONEXION MUCHOS-MUCHOS ACTOR-PELICULAS
CREATE TABLE ACTOR_PELICULA(

    CODIGO_ACTOR_PELICULA SERIAL PRIMARY KEY,
    CODIGO_ACTOR INT,
    CODIGO_PELICULA INT,
    CONSTRAINT FK_CODIGO_ACTOR FOREIGN KEY(CODIGO_ACTOR) REFERENCES ACTOR(CODIGO_ACTOR),
    CONSTRAINT FK_CODIGO_PELICULA FOREIGN KEY(CODIGO_PELICULA) REFERENCES PELICULA(CODIGO_PELICULA)

);

-- TABLA DE TRADUCCION
CREATE TABLE TRADUCCION(

    CODIGO_TRADUCCION SERIAL PRIMARY KEY,
    IDIOMA VARCHAR(50) NOT NULL
    
);

-- TABLA CONEXION MUCHOS-MUCHOS TRADUCCION-PELICULAS
CREATE TABLE TRADUCCION_PELICULA(

    CODIGO_TRADUCCION_PELICULA SERIAL PRIMARY KEY,
    CODIGO_TRADUCCION INT,
    CODIGO_PELICULA INT,
    CONSTRAINT FK_CODIGO_TRADUCCION FOREIGN KEY(CODIGO_TRADUCCION) REFERENCES TRADUCCION(CODIGO_TRADUCCION),
    CONSTRAINT FK_CODIGO_PELICULA FOREIGN KEY(CODIGO_PELICULA) REFERENCES PELICULA(CODIGO_PELICULA)

);