-- CONTEO PAISES
SELECT COUNT(*) AS PAISES FROM PAIS;

-- CONTEO CIUDADES
SELECT COUNT(*) AS CIUDADES FROM CIUDAD;

-- CONTEO CLIENTES
SELECT COUNT(*) AS CLIENTES FROM CLIENTE;

-- CONTEO EMPLEADOS
SELECT COUNT(*) AS EMPLEADOS FROM EMPLEADO;

-- CONTEO TIENDAS
SELECT COUNT(*) AS TIENDAS FROM TIENDA;

-- CONTEO RETNAS
SELECT COUNT(*) AS RENTAS FROM RENTA;

-- CONTEO PELICULAS
SELECT COUNT(*) AS PELICULAS FROM PELICULA;

-- CONTEO INVENTARIO
SELECT COUNT(*) AS INVENTARIO FROM PELICULA_TIENDA;

-- CONTEO CATEGORIAS
SELECT COUNT(*) AS CATEGORIAS FROM CATEGORIA;

-- CONTEO ACTORES
SELECT COUNT(*) AS ACTORES FROM ACTOR;

-- CONTEO TRADUCCIONES
SELECT COUNT(*) AS TRADUCCIONES FROM TRADUCCION;

-- CONTEO CATEGORIA_PELICULA
SELECT COUNT(*) AS CATEGORIA_PELICULA FROM CATEGORIA_PELICULA;

-- CONTEO ACTOR_PELICULA
SELECT COUNT(*) AS ACTOR_PELICULA FROM ACTOR_PELICULA;

-- CONTEO TRADUCCION_PELICULA
SELECT COUNT(*) AS TRADUCCION_PELICULA FROM TRADUCCION_PELICULA;