-- TABLA DE PAISES
CREATE TABLE PAIS(

    CODIGO_PAIS SERIAL PRIMARY KEY,
    NOMBRE_PAIS VARCHAR(50) NOT NULL
    
);

-- TABLA DE CIUDADES
CREATE TABLE CIUDAD(

    CODIGO_CIUDAD SERIAL PRIMARY KEY,
    NOMBRE_CIUDAD VARCHAR(50) NOT NULL,
    CODIGO_POSTAL_CIUDAD INT,
    CODIGO_PAIS INT,
    CONSTRAINT FK_CODIGO_PAIS FOREIGN KEY(CODIGO_PAIS) REFERENCES PAIS(CODIGO_PAIS)

);

-- TABLA DE TIENDAS
CREATE TABLE TIENDA(

    CODIGO_TIENDA SERIAL PRIMARY KEY,
    DIRECCION_TIENDA VARCHAR(100) NOT NULL,
    NOMBRE_TIENDA VARCHAR(50) NOT NULL,
    CODIGO_POSTAL_TIENDA INT

);

-- TABLA DE CLIENTES
CREATE TABLE CLIENTE(

    CODIGO_CLIENTE SERIAL PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR(50) NOT NULL,
    APELLIDO_CLIENTE VARCHAR(50) NOT NULL,
    DIRECCION_CLIENTE VARCHAR(100) NOT NULL,
    CORREO_ELECTRONICO_CLIENTE VARCHAR(100) NOT NULL,
    FECHA_REGISTRO_CLIENTE TIMESTAMP NOT NULL,
    CODIGO_POSTAL_CLIENTE INT,
    ESTADO_CLIENTE VARCHAR(5) NOT NULL,
    CODIGO_TIENDA INT,
    CODIGO_CIUDAD INT,
    CONSTRAINT FK_CODIGO_TIENDA FOREIGN KEY(CODIGO_TIENDA) REFERENCES TIENDA(CODIGO_TIENDA),
    CONSTRAINT FK_CODIGO_CIUDAD FOREIGN KEY(CODIGO_CIUDAD) REFERENCES CIUDAD(CODIGO_CIUDAD)

);

--TABLA DE EMPLEADOS
CREATE TABLE EMPLEADO(

    CODIGO_EMPLEADO SERIAL PRIMARY KEY,
    NOMBRE_EMPLEADO VARCHAR(50) NOT NULL,
    APELLIDO_EMPLEADO VARCHAR(50) NOT NULL,
    DIRECCION_EMPLEADO VARCHAR(100) NOT NULL,
    CORREO_ELECTRONICO_EMPLEADO VARCHAR(100) NOT NULL,
    CODIGO_POSTAL_EMPLEADO INT,
    ESTADO_EMPLEADO VARCHAR(5) NOT NULL,
    USUARIO_EMPLEADO VARCHAR(50) NOT NULL,
    CONTRASENA_EMPLEADO VARCHAR(100) NOT NULL,
    CODIGO_TIENDA INT,
    CONSTRAINT FK_CODIGO_TIENDA FOREIGN KEY(CODIGO_TIENDA) REFERENCES TIENDA(CODIGO_TIENDA)

);

-- TABLA DE PELICULAS
CREATE TABLE PELICULA(

    CODIGO_PELICULA SERIAL PRIMARY KEY,
    TITULO_PELICULA VARCHAR(50) NOT NULL,
    DESCRIPCION_PELICULA VARCHAR(500) NOT NULL,
    FECHA_ESTRENO_PELICULA VARCHAR(100) NOT NULL,
    COSTO_RENTA_PELICULA FLOAT NOT NULL,
    COSTO_MORA_PELICULA FLOAT NOT NULL,
    CLASIFICACION_PELICULA VARCHAR(50) NOT NULL,
    IDIOMA_ORIGEN_PELICULA VARCHAR(50) NOT NULL,
    DURACION INT NOT NULL,
    TIEMPO_RENTA_PELICULA INT NOT NULL
);

-- TABLA CONEXION MM PELICULAS-TIENDA
CREATE TABLE PELICULA_TIENDA(

    CODIGO_PELICULA_TIENDA SERIAL PRIMARY KEY,
    CANTIDAD_COPIAS INT,
    CODIGO_TIENDA INT,
    CODIGO_PELICULA INT,
    CONSTRAINT FK_CODIGO_TIENDA FOREIGN KEY(CODIGO_TIENDA) REFERENCES TIENDA(CODIGO_TIENDA),
    CONSTRAINT FK_CODIGO_PELICULA FOREIGN KEY(CODIGO_PELICULA) REFERENCES PELICULA(CODIGO_PELICULA)

);

-- TABLA RENTA DE PELICULAS
CREATE TABLE RENTA(

    CODIGO_RENTA SERIAL PRIMARY KEY,
    CANTIDAD_PAGO_RENTA FLOAT,
    FECHA_RENTA TIMESTAMP,
    FECHA_RETORNO TIMESTAMP,
    CODIGO_CLIENTE INT,
    CODIGO_EMPLEADO INT,
    CODIGO_PELICULA INT,
    CONSTRAINT FK_CODIGO_CLIENTE FOREIGN KEY(CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE),
    CONSTRAINT FK_CODIGO_EMPLEADO FOREIGN KEY(CODIGO_EMPLEADO) REFERENCES EMPLEADO(CODIGO_EMPLEADO),
    CONSTRAINT FK_CODIGO_PELICULA FOREIGN KEY(CODIGO_PELICULA) REFERENCES PELICULA(CODIGO_PELICULA)

);

-- TABLA DE CATEGORIAS
CREATE TABLE CATEGORIA(

    CODIGO_CATEGORIA SERIAL PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR(50) NOT NULL
    
);

-- TABLA CONEXION MUCHOS-MUCHOS CATEGORIAS-PELICULAS
CREATE TABLE CATEGORIA_PELICULA(

    CODIGO_CATEGORIA_PELICULA SERIAL PRIMARY KEY,
    CODIGO_CATEGORIA INT,
    CODIGO_PELICULA INT,
    CONSTRAINT FK_CODIGO_CATEGORIA FOREIGN KEY(CODIGO_CATEGORIA) REFERENCES CATEGORIA(CODIGO_CATEGORIA),
    CONSTRAINT FK_CODIGO_PELICULA FOREIGN KEY(CODIGO_PELICULA) REFERENCES PELICULA(CODIGO_PELICULA)

);

-- TABLA DE ACTORES
CREATE TABLE ACTOR(

    CODIGO_ACTOR SERIAL PRIMARY KEY,
    NOMBRE_ACTOR VARCHAR(50) NOT NULL,
    APELLIDO_ACTOR VARCHAR(50) NOT NULL
    
);

-- TABLA CONEXION MUCHOS-MUCHOS ACTOR-PELICULAS
CREATE TABLE ACTOR_PELICULA(

    CODIGO_ACTOR_PELICULA SERIAL PRIMARY KEY,
    CODIGO_ACTOR INT,
    CODIGO_PELICULA INT,
    CONSTRAINT FK_CODIGO_ACTOR FOREIGN KEY(CODIGO_ACTOR) REFERENCES ACTOR(CODIGO_ACTOR),
    CONSTRAINT FK_CODIGO_PELICULA FOREIGN KEY(CODIGO_PELICULA) REFERENCES PELICULA(CODIGO_PELICULA)

);

-- TABLA DE TRADUCCION
CREATE TABLE TRADUCCION(

    CODIGO_TRADUCCION SERIAL PRIMARY KEY,
    IDIOMA VARCHAR(50) NOT NULL
    
);

-- TABLA CONEXION MUCHOS-MUCHOS TRADUCCION-PELICULAS
CREATE TABLE TRADUCCION_PELICULA(

    CODIGO_TRADUCCION_PELICULA SERIAL PRIMARY KEY,
    CODIGO_TRADUCCION INT,
    CODIGO_PELICULA INT,
    CONSTRAINT FK_CODIGO_TRADUCCION FOREIGN KEY(CODIGO_TRADUCCION) REFERENCES TRADUCCION(CODIGO_TRADUCCION),
    CONSTRAINT FK_CODIGO_PELICULA FOREIGN KEY(CODIGO_PELICULA) REFERENCES PELICULA(CODIGO_PELICULA)

);




-- LLENANDO LA TABLA DE PAISES
INSERT INTO PAIS(NOMBRE_PAIS) 
    SELECT DISTINCT NOMBRE
FROM(
        SELECT DISTINCT PAIS_CLIENTE AS NOMBRE FROM TEMPORAL
        UNION
        SELECT DISTINCT PAIS_EMPLEADO AS NOMBRE FROM TEMPORAL
        UNION
        SELECT DISTINCT PAIS_CLIENTE AS NOMBRE FROM TEMPORAL 
    ) AS FOO
WHERE
    NOMBRE
IS NOT NULL;

-- LLENANDO LA TABLA DE CIUDADES
INSERT INTO CIUDAD(NOMBRE_CIUDAD, CODIGO_POSTAL_CIUDAD, CODIGO_PAIS)
    SELECT DISTINCT NOMBRE, CODIGO_POSTAL, CODIGO_PAIS
FROM (
    SELECT DISTINCT
        CIUDAD_CLIENTE AS NOMBRE,
        CODIGO_POSTAL_CLIENTE AS CODIGO_POSTAL,
        CODIGO_PAIS FROM TEMPORAL INNER JOIN PAIS ON PAIS_CLIENTE = NOMBRE_PAIS
) AS FOO
WHERE
    NOMBRE
IS NOT NULL;

-- LENANDO LA TABLA DE TIENDAS
INSERT INTO TIENDA(DIRECCION_TIENDA, NOMBRE_TIENDA, CODIGO_POSTAL_TIENDA)
    SELECT DISTINCT DIRECCION, NOMBRE, CODIGO_POSTAL
FROM(
    SELECT DISTINCT
        CIUDAD_TIENDA AS DIRECCION,
        NOMBRE_TIENDA AS NOMBRE,
        CODIGO_POSTAL_TIENDA  AS CODIGO_POSTAL
        FROM TEMPORAL
) AS FOO
WHERE
    NOMBRE
IS NOT NULL;


--LLENANDO TABLA CLIENTES
INSERT INTO CLIENTE(NOMBRE_CLIENTE, APELLIDO_CLIENTE, DIRECCION_CLIENTE, 
    CORREO_ELECTRONICO_CLIENTE, FECHA_REGISTRO_CLIENTE, CODIGO_POSTAL_CLIENTE,
    ESTADO_CLIENTE, CODIGO_TIENDA, CODIGO_CIUDAD)
SELECT DISTINCT NOMBRE, APELLIDO, DIRECCION, CORREO, FECHA, CODIGO_POSTAL,
        ESTADO, CODIGO_TIENDA, CODIGO_CIUDAD
FROM(
    SELECT
        SPLIT_PART(NOMBRE_CLIENTE, ' ', 1) AS NOMBRE,
        SPLIT_PART(NOMBRE_CLIENTE, ' ', 2) AS APELLIDO,
        DIRECCION_CLIENTE AS DIRECCION,
        CORREO_CLIENTE AS CORREO,
        FECHA_CREACION AS FECHA,
        CODIGO_POSTAL_CLIENTE AS CODIGO_POSTAL,
        CLIENTE_ACTIVO AS ESTADO,
        CODIGO_TIENDA, CODIGO_CIUDAD
        FROM TEMPORAL 
            INNER JOIN TIENDA ON TIENDA_PREFERIDA = TIENDA.NOMBRE_TIENDA
            INNER JOIN CIUDAD ON CIUDAD_CLIENTE = CIUDAD.NOMBRE_CIUDAD AND CODIGO_POSTAL_CLIENTE = CIUDAD.CODIGO_POSTAL_CIUDAD
            INNER JOIN PAIS ON PAIS.NOMBRE_PAIS = PAIS_CLIENTE AND CIUDAD.CODIGO_PAIS = PAIS.CODIGO_PAIS
) AS TA
WHERE
    NOMBRE IS NOT NULL 
    AND APELLIDO IS NOT NULL
    AND FECHA IS NOT NULL
ORDER BY
    NOMBRE
ASC;


-- LLENANDO TABLA DE EMPLEADOS
INSERT INTO EMPLEADO(NOMBRE_EMPLEADO, APELLIDO_EMPLEADO, DIRECCION_EMPLEADO, 
    CORREO_ELECTRONICO_EMPLEADO, CODIGO_POSTAL_EMPLEADO, ESTADO_EMPLEADO, 
    USUARIO_EMPLEADO, CONTRASENA_EMPLEADO, CODIGO_TIENDA)
SELECT DISTINCT NOMBRE, APELLIDO, DIRECCION, CORREO, CODIGO_POSTAL, ESTADO, USUARIO, 
    CONTRASENA, CODIGO_TIENDA
FROM(
    SELECT 
        SPLIT_PART(NOMBRE_EMPLEADO, ' ', 1) AS NOMBRE,
        SPLIT_PART(NOMBRE_EMPLEADO, ' ', 2) AS APELLIDO,
        DIRECCION_EMPLEADO AS DIRECCION,
        CORREO_EMPLEADO AS CORREO,
        CODIGO_POSTAL_EMPLEADO AS CODIGO_POSTAL,
        EMPLEADO_ACTIVO AS ESTADO,
        USUARIO_EMPLEADO AS USUARIO, 
        CONTRASENA_EMPLEADO AS CONTRASENA,
        CODIGO_TIENDA
        FROM TEMPORAL
            INNER JOIN TIENDA ON TIENDA_EMPLEADO = TIENDA.NOMBRE_TIENDA
) AS TA
WHERE
    NOMBRE IS NOT NULL 
    AND APELLIDO IS NOT NULL;


-- LLENANDO TABLA DE PELICULAS
INSERT INTO PELICULA(TITULO_PELICULA, DESCRIPCION_PELICULA, 
    FECHA_ESTRENO_PELICULA, COSTO_RENTA_PELICULA, COSTO_MORA_PELICULA, 
    CLASIFICACION_PELICULA, IDIOMA_ORIGEN_PELICULA, DURACION,
    TIEMPO_RENTA_PELICULA)
SELECT DISTINCT TITULO, DESCRIPCION, FECHA_ESTRENO, COSTO_RENTA,
     COSTO_MORA, CLASIFICACION, IDIOMA_ORIGEN, DURACION, TIEMPO_RENTA
FROM(
    SELECT
        NOMBRE_PELICULA AS TITULO,
        DESCRIPCION_PELICULA AS DESCRIPCION,
        ANO_LANZAMIENTO AS FECHA_ESTRENO,
        COSTO_RENTA AS COSTO_RENTA,
        COSTO_POR_DANO AS COSTO_MORA,
        CLASIFICACION AS CLASIFICACION,
        LENGUAJE_PELICULA AS IDIOMA_ORIGEN,
        DURACION AS DURACION,
        DIAS_RENTA AS TIEMPO_RENTA
        FROM TEMPORAL
) AS TA 
WHERE 
    TITULO IS NOT NULL;


-- LLENANDO TABLA DE PELICULA-TIENDA
INSERT INTO PELICULA_TIENDA(CANTIDAD_COPIAS, CODIGO_TIENDA, CODIGO_PELICULA)
SELECT DISTINCT COUNT(*), CODIGO_TIENDA, CODIGO_PELICULA 
FROM TEMPORAL 
    INNER JOIN TIENDA ON TIENDA.NOMBRE_TIENDA = TIENDA_PELICULA
    INNER JOIN PELICULA ON PELICULA.TITULO_PELICULA = NOMBRE_PELICULA 
GROUP BY
    CODIGO_TIENDA, CODIGO_PELICULA;

-- LLENANDO TABLA DE RENTA
INSERT INTO RENTA(CANTIDAD_PAGO_RENTA, FECHA_RENTA, FECHA_RETORNO, 
    CODIGO_CLIENTE, CODIGO_EMPLEADO, CODIGO_PELICULA)
SELECT DISTINCT CANTIDAD_PAGO, FECHA_RENTA, FECHA_RETORNO, 
    CODIGO_CLIENTE, CODIGO_EMPLEADO, CODIGO_PELICULA
FROM(
    SELECT DISTINCT
        MONTO_A_PAGAR AS CANTIDAD_PAGO,
        FECHA_RENTA AS FECHA_RENTA,
        FECHA_RETORNO AS FECHA_RETORNO,
        CODIGO_CLIENTE, CODIGO_EMPLEADO, CODIGO_PELICULA
        FROM TEMPORAL
        INNER JOIN CLIENTE ON  CLIENTE.NOMBRE_CLIENTE || ' ' || 
            CLIENTE.APELLIDO_CLIENTE =  TEMPORAL.NOMBRE_CLIENTE
        INNER JOIN EMPLEADO ON EMPLEADO.NOMBRE_EMPLEADO || ' ' ||
            EMPLEADO.APELLIDO_EMPLEADO = TEMPORAL.NOMBRE_EMPLEADO
        INNER JOIN PELICULA ON NOMBRE_PELICULA = PELICULA.TITULO_PELICULA
)AS TA
WHERE   
    CANTIDAD_PAGO IS NOT NULL 
    AND FECHA_RENTA IS NOT NULL;



-- LLENANDO TABLA DE CATEGORIAS
INSERT INTO CATEGORIA(NOMBRE_CATEGORIA)
SELECT DISTINCT CATEGORIA_PELICULA FROM TEMPORAL
WHERE CATEGORIA_PELICULA IS NOT NULL;


-- LLENANDO TABLA DE CATEGORIA-PELICULA
INSERT INTO CATEGORIA_PELICULA(CODIGO_CATEGORIA, CODIGO_PELICULA)
SELECT DISTINCT CODIGO_CATEGORIA, CODIGO_PELICULA
FROM TEMPORAL 
    INNER JOIN CATEGORIA ON CATEGORIA.NOMBRE_CATEGORIA = CATEGORIA_PELICULA
    INNER JOIN PELICULA ON PELICULA.TITULO_PELICULA = NOMBRE_PELICULA
GROUP BY
    CODIGO_CATEGORIA, CODIGO_PELICULA;


-- LLENANDO TABLA DE ACTORES
INSERT INTO ACTOR(NOMBRE_ACTOR, APELLIDO_ACTOR)
SELECT DISTINCT NOMBRE, APELLIDO
FROM(
    SELECT
        SPLIT_PART(ACTOR_PELICULA, ' ', 1) AS NOMBRE,
        SPLIT_PART(ACTOR_PELICULA, ' ', 2) AS APELLIDO
        FROM TEMPORAL
) AS TA
WHERE
    NOMBRE IS NOT NULL
    AND APELLIDO IS NOT NULL;


-- LLENANDO TABLA DE ACTOR-PELICULA
INSERT INTO ACTOR_PELICULA(CODIGO_ACTOR, CODIGO_PELICULA)
SELECT DISTINCT CODIGO_ACTOR, CODIGO_PELICULA
FROM TEMPORAL 
    INNER JOIN ACTOR ON ACTOR.NOMBRE_ACTOR || ' ' || ACTOR.APELLIDO_ACTOR = ACTOR_PELICULA
    INNER JOIN PELICULA ON PELICULA.TITULO_PELICULA = NOMBRE_PELICULA
GROUP BY
    CODIGO_ACTOR, CODIGO_PELICULA;


-- LLENANDO TABLA DE TRADUCCIONES
INSERT INTO TRADUCCION(IDIOMA)
SELECT DISTINCT LENGUAJE_PELICULA
FROM TEMPORAL
WHERE LENGUAJE_PELICULA IS NOT NULL;


-- LLENANDO TABLA DE TRADUCCION-PELICULA
INSERT INTO TRADUCCION_PELICULA(CODIGO_TRADUCCION, CODIGO_PELICULA)
SELECT DISTINCT CODIGO_TRADUCCION, CODIGO_PELICULA
FROM TEMPORAL 
    INNER JOIN TRADUCCION ON TRADUCCION.IDIOMA = LENGUAJE_PELICULA
    INNER JOIN PELICULA ON PELICULA.TITULO_PELICULA = NOMBRE_PELICULA
GROUP BY
    CODIGO_TRADUCCION, CODIGO_PELICULA;