DROP TABLE 
    ACTOR,
    CATEGORIA,
    TRADUCCION, 
    CIUDAD,
    CLIENTE, 
    EMPLEADO,
    PAIS,
    PELICULA,
    PELICULA_TIENDA,
    RENTA,
    TIENDA,
    TRADUCCION,
    CATEGORIA_PELICULA,
    ACTOR_PELICULA,
    TRADUCCION_PELICULA
;