SELECT CA.PAIS, CA.NO_PELICULAS_CATE_SPORTS, CB.RENTAS_SUMA AS TOTAL_RENTAS_POR_PAIS,
    ((CA.NO_PELICULAS_CATE_SPORTS * 100) / CB.RENTAS_SUMA) AS PORCENTAJE
FROM(
    SELECT TA.PAIS AS PAIS , COUNT(TB.NOMBRE_CATEGORIA) AS NO_PELICULAS_CATE_SPORTS
    FROM(
        SELECT TD.PAIS AS PAIS, TD.CIUDAD , CODIGO_RENTA AS CODIGO_PELICULA
        FROM(
            SELECT CIUDAD.NOMBRE_CIUDAD AS CIUDAD,
            PAIS.NOMBRE_PAIS AS PAIS, RENTA.CODIGO_PELICULA AS CODIGO_RENTA
            FROM PAIS, CIUDAD, CLIENTE, RENTA
            WHERE 
                PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
                AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
                AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
            GROUP BY
                CIUDAD.NOMBRE_CIUDAD,
                PAIS.NOMBRE_PAIS, RENTA.CODIGO_PELICULA
        ) TD
        GROUP BY 
            PAIS, CIUDAD, CODIGO_RENTA
    ) TA,
    (
        SELECT PELICULA.CODIGO_PELICULA AS CODIGO_PELICULA,  PELICULA.TITULO_PELICULA AS TITULO_PELICULA, 
            CATEGORIA.NOMBRE_CATEGORIA AS NOMBRE_CATEGORIA
        FROM PELICULA, CATEGORIA, CATEGORIA_PELICULA
        WHERE
            CATEGORIA.NOMBRE_CATEGORIA = 'Sports'
            AND CATEGORIA_PELICULA.CODIGO_PELICULA = PELICULA.CODIGO_PELICULA
            AND CATEGORIA_PELICULA.CODIGO_CATEGORIA= CATEGORIA.CODIGO_CATEGORIA
        GROUP BY
            PELICULA.CODIGO_PELICULA, PELICULA.TITULO_PELICULA, CATEGORIA.NOMBRE_CATEGORIA           
    ) TB
    WHERE
        TA.CODIGO_PELICULA = TB.CODIGO_PELICULA
    GROUP BY
        PAIS
) CA,
(
    SELECT TD.PAIS AS PAIS , SUM(RENTAS) AS RENTAS_SUMA
    FROM(
        SELECT CIUDAD.NOMBRE_CIUDAD AS CIUDAD,
        PAIS.NOMBRE_PAIS AS PAIS, COUNT(*) AS RENTAS
        FROM PAIS, CIUDAD, CLIENTE, RENTA
        WHERE 
            PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
            AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
            AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
        GROUP BY
            CIUDAD.NOMBRE_CIUDAD,
            PAIS.NOMBRE_PAIS
    ) TD
    GROUP BY 
        PAIS    
) CB
WHERE
    CA.PAIS = CB.PAIS
ORDER BY
    PAIS ASC
;