SELECT CC.NOMBRE_PAIS, CC.NOMBRE_COMPLETO, CC.RENTAS_MAXIMAS, CD.RENTAS_SUMA, 
    (CC.RENTAS_MAXIMAS * 100)/CD.RENTAS_SUMA AS PORCENTAJE
FROM(
    SELECT CA.NOMBRE_PAIS AS NOMBRE_PAIS, CA.NOMBRE_COMPLETO AS NOMBRE_COMPLETO, CA.RENTAS_MAXIMAS AS RENTAS_MAXIMAS
    FROM(
        SELECT NOMBRE_PAIS , NOMBRE_COMPLETO, RENTAS_MAXIMAS
        FROM(
            SELECT PAIS AS NOMBRE_PAIS , MAX(RENTAS) AS RENTAS_MAXIMAS
            FROM(
                SELECT CLIENTE.CODIGO_CLIENTE, CLIENTE.NOMBRE_CLIENTE || ' ' || CLIENTE.APELLIDO_CLIENTE
                AS NOMBRE_COMPLETO, PAIS.NOMBRE_PAIS AS PAIS, COUNT(*) AS RENTAS
                FROM PAIS, CIUDAD, CLIENTE, RENTA
                WHERE 
                    PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
                    AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
                    AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
                GROUP BY
                    CLIENTE.CODIGO_CLIENTE, CLIENTE.NOMBRE_CLIENTE || ' ' || CLIENTE.APELLIDO_CLIENTE, 
                    PAIS.NOMBRE_PAIS
            ) TA
            GROUP BY PAIS
        )
        MAX_POR_PAIS,
        (
            SELECT CLIENTE.CODIGO_CLIENTE, CLIENTE.NOMBRE_CLIENTE || ' ' || CLIENTE.APELLIDO_CLIENTE
                AS NOMBRE_COMPLETO, PAIS.NOMBRE_PAIS AS PAIS, COUNT(*) AS RENTAS
            FROM PAIS, CIUDAD, CLIENTE, RENTA
            WHERE 
                PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
                AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
                AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
            GROUP BY
                CLIENTE.CODIGO_CLIENTE, CLIENTE.NOMBRE_CLIENTE || ' ' || CLIENTE.APELLIDO_CLIENTE, 
                PAIS.NOMBRE_PAIS

        ) POR_CLIENTE

        WHERE POR_CLIENTE.PAIS = MAX_POR_PAIS.NOMBRE_PAIS 
            AND POR_CLIENTE.RENTAS = MAX_POR_PAIS.RENTAS_MAXIMAS
        ORDER BY
            RENTAS_MAXIMAS DESC LIMIT 1
    ) CA
) CC,
(
    SELECT TD.PAIS AS NOMBRE_PAIS , SUM(RENTAS) AS RENTAS_SUMA
    FROM(
        SELECT CLIENTE.CODIGO_CLIENTE, CLIENTE.NOMBRE_CLIENTE || ' ' || CLIENTE.APELLIDO_CLIENTE
        AS NOMBRE_COMPLETO, PAIS.NOMBRE_PAIS AS PAIS, COUNT(*) AS RENTAS
        FROM PAIS, CIUDAD, CLIENTE, RENTA
        WHERE 
            PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
            AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
            AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
        GROUP BY
            CLIENTE.CODIGO_CLIENTE, CLIENTE.NOMBRE_CLIENTE || ' ' || CLIENTE.APELLIDO_CLIENTE, 
            PAIS.NOMBRE_PAIS
    ) TD
    GROUP BY PAIS
) CD
WHERE 
    CC.NOMBRE_PAIS = CD.NOMBRE_PAIS
;