SELECT SUMA_DE_RENTAS.PAIS, SUMA_DE_RENTAS.CIUDAD, SUMA_DE_RENTAS.RENTAS, CIUDADES_POR_PAIS.CIUDADES, SUMA_DE_RENTAS.RENTAS::FLOAT / CIUDADES_POR_PAIS.CIUDADES::FLOAT AS PROMEDIO
FROM(
    SELECT PAIS.NOMBRE_PAIS AS PAIS, COUNT(*) AS RENTAS, CIUDAD.NOMBRE_CIUDAD AS CIUDAD
    FROM PAIS, CIUDAD, CLIENTE, RENTA
    WHERE
        PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
        AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
        AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
    GROUP BY
        PAIS.NOMBRE_PAIS, CIUDAD.NOMBRE_CIUDAD
) SUMA_DE_RENTAS,
(
    SELECT PAIS.NOMBRE_PAIS AS  PAIS, COUNT(*) AS CIUDADES
    FROM PAIS, CIUDAD
    WHERE
        PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
    GROUP BY
        PAIS.NOMBRE_PAIS
) CIUDADES_POR_PAIS
WHERE
    SUMA_DE_RENTAS.PAIS = CIUDADES_POR_PAIS.PAIS
ORDER BY
    PAIS ASC
;