SELECT  SUM(CANTIDAD_COPIAS)
FROM TIENDA, PELICULA_TIENDA, PELICULA
WHERE TIENDA.CODIGO_TIENDA = PELICULA_TIENDA.CODIGO_TIENDA 
    AND PELICULA.CODIGO_PELICULA = PELICULA_TIENDA.CODIGO_PELICULA
    AND PELICULA.TITULO_PELICULA = 'SUGAR WONKA';