SELECT CLIENTE.NOMBRE_CLIENTE, CLIENTE.APELLIDO_CLIENTE, 
    SUM(RENTA.CANTIDAD_PAGO_RENTA) AS TOTAL
FROM RENTA, CLIENTE
WHERE CLIENTE.CODIGO_CLIENTE = RENTA.CODIGO_CLIENTE
GROUP BY CLIENTE.NOMBRE_CLIENTE, CLIENTE.APELLIDO_CLIENTE
HAVING 40 <= COUNT(*);