SELECT TD.PAIS AS PAIS , TD.CIUDAD, SUM(RENTAS) AS RENTAS_POR_CIUDAD
FROM(
    SELECT CIUDAD.NOMBRE_CIUDAD AS CIUDAD,
    PAIS.NOMBRE_PAIS AS PAIS, COUNT(*) AS RENTAS
    FROM PAIS, CIUDAD, CLIENTE, RENTA
    WHERE 
        PAIS.CODIGO_PAIS = CIUDAD.CODIGO_PAIS
        AND CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
        AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
    GROUP BY
        CIUDAD.NOMBRE_CIUDAD,
        PAIS.NOMBRE_PAIS
) TD
WHERE
    PAIS = 'United States'
GROUP BY 
    PAIS, CIUDAD
HAVING 
    SUM(RENTAS) > (
        SELECT COUNT(*)
        FROM CIUDAD, CLIENTE, RENTA
        WHERE
            CIUDAD.CODIGO_CIUDAD = CLIENTE.CODIGO_CIUDAD
            AND RENTA.CODIGO_CLIENTE = CLIENTE.CODIGO_CLIENTE
            AND CIUDAD.NOMBRE_CIUDAD = 'Dayton'
        GROUP BY
            CIUDAD.NOMBRE_CIUDAD
    )
ORDER BY
    RENTAS_POR_CIUDAD DESC
;