SELECT DISTINCT NOMBRE_ACTOR, APELLIDO_ACTOR, FECHA_ESTRENO_PELICULA
FROM ACTOR_PELICULA, ACTOR, PELICULA
WHERE PELICULA.DESCRIPCION_PELICULA LIKE '%Crocodile%'
    AND PELICULA.DESCRIPCION_PELICULA LIKE '%Shark%'
    AND ACTOR_PELICULA.CODIGO_ACTOR = ACTOR.CODIGO_ACTOR
    AND ACTOR_PELICULA.CODIGO_PELICULA = PELICULA.CODIGO_PELICULA
ORDER BY APELLIDO_ACTOR ASC;